version : "3"
services:
    app:
      build:
        context: ./
        dockerfile: ./php/Dockerfile
      container_name: wemall-app
      restart: always
      working_dir: /var/www/
      volumes:
        - ..:/var/www
    nginx:
      image: nginx:latest
      container_name: wemall-server
      restart: always
      ports:
        - "8000:80"
      volumes:
        - ..:/var/www
        - ../config/nginx/:/etc/nginx/conf.d