version : "3"
services:
    web-server:
      image: nginx:latest
      ports: 
        - "4400:80"
      volumes:
        - ../config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    php-app:
      build: 
        dockerfile: ./Dockerfile
      volumes:
        - ../:/app
    app-db:
      image: mysql:latest
      volumes:
        - mysqldata:/var/lib/mysql
      ports:
        - "4306:3306"
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USER: user
        MYSQL_PASSWORD: secret
        MYSQL_DATABASE: wemall3
volumes:
  mysqldata:
